blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/LukeS-05/LukeS-05.github.io/issues/new?template=ppk-docs.md
    about: Please report documentation problems on my website repo.